import { useEffect,useMemo,useState } from "react";
import {AlertTriangle,BookOpenCheck,Building2,CheckCircle2,ChevronRight,CircleUserRound,Clock3,FileClock,Globe2,History,LayoutDashboard,Loader2,LogOut,Menu,Plus,RefreshCw,Settings,Shield,ShieldAlert,Siren,X} from "lucide-react";
import {api} from "./api"; import {supabase} from "./supabase";
type View="summary"|"risks"|"assets"|"incidents"|"coach"|"history"|"settings";
type Asset={id:string;value:string;verification_status:"pending"|"verified";created_at:string};
type Finding={id:string;asset_id:string;title:string;severity:"critical"|"high"|"medium"|"low"|"info";status:"open"|"accepted"|"resolved";evidence:string;score_impact:number;control_key:string;detected_at:string};
type Scan={id:string;asset_id:string;score:number;scanned_at:string;checks:{https:boolean;spf:boolean;dmarc:boolean;securityHeaders:number}};
type Incident={id:string;title:string;description:string;severity:string;status:"open"|"contained"|"resolved";created_at:string};
type Audit={id:string;action:string;created_at:string}; type Org={id:string;name:string;slug:string;role:string;sector?:string;employee_count?:number};
type Dashboard={assets:Asset[];findings:Finding[];history:Scan[];incidents:Incident[];audits:Audit[]};
const empty:Dashboard={assets:[],findings:[],history:[],incidents:[],audits:[]};
const labels:Record<View,string>={summary:"Resumen",risks:"Riesgos",assets:"Activos",incidents:"Incidentes",coach:"CyberCoach",history:"Historial",settings:"Configuración"};
const guide:Record<string,{title:string;why:string;steps:string[]}>= {"web.https":{title:"Protege tu sitio con HTTPS",why:"HTTPS protege datos y contraseñas mientras viajan por internet.",steps:["Activa un certificado TLS con tu hosting.","Redirige HTTP hacia HTTPS.","Vuelve a analizar el dominio."]},"email.spf":{title:"Autoriza el correo con SPF",why:"SPF indica qué servicios pueden enviar correo por tu dominio.",steps:["Identifica tus proveedores de correo.","Publica un único TXT SPF en el dominio raíz.","Valida y vuelve a analizar."]},"email.dmarc":{title:"Evita suplantación con DMARC",why:"DMARC reduce correos falsos enviados en nombre de tu empresa.",steps:["Crea el registro _dmarc.","Inicia con p=none y una dirección de reportes.","Avanza gradualmente a quarantine o reject."]},"web.headers":{title:"Refuerza tu sitio web",why:"Estos encabezados limitan ataques comunes en el navegador.",steps:["Configura HSTS, CSP y X-Content-Type-Options.","Prueba que tu sitio siga funcionando.","Ejecuta un nuevo análisis."]}};
const fmt=(v:string)=>new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export function App(){
 const [session,setSession]=useState<any>(null),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[data,setData]=useState<Dashboard>(empty),[domain,setDomain]=useState(""),[dns,setDns]=useState<any>(null),[loading,setLoading]=useState(false),[org,setOrg]=useState<Org|null>(null),[view,setView]=useState<View>("summary"),[mobile,setMobile]=useState(false);
 const [incident,setIncident]=useState({title:"",description:"",severity:"medium"}),[company,setCompany]=useState({name:"TestCompCy",sector:"",employeeCount:""});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)void bootstrap()},[session]);
 const score=data.history[0]?.score??0,open=data.findings.filter(f=>f.status==="open"),active=data.incidents.filter(i=>i.status!=="resolved"),trend=data.history.length>1?score-data.history[1].score:0;
 const latest=useMemo(()=>new Map(data.history.map(s=>[s.asset_id,s])),[data.history]);
 async function bootstrap(){try{const r=await api.organizations(),o=r.organizations?.[0];if(!o)throw new Error("No encontramos una empresa asociada.");setOrg(o);setCompany({name:o.name,sector:o.sector??"",employeeCount:o.employee_count?.toString()??""});setData(await api.dashboard(o.id))}catch(e){setMessage((e as Error).message)}}
 async function load(){if(org)setData(await api.dashboard(org.id))}
 async function act(fn:()=>Promise<unknown>,ok:string){setLoading(true);try{await fn();await load();setMessage(ok)}catch(e){setMessage((e as Error).message)}finally{setLoading(false)}}
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setMessage(error?error.message:"Te enviamos un enlace seguro a tu correo.");setLoading(false)}
 async function addDomain(e:React.FormEvent){e.preventDefault();if(!org)return;setLoading(true);try{setDns(await api.createDomain(org.id,domain));setMessage("")}catch(e){setMessage((e as Error).message)}finally{setLoading(false)}}
 async function verify(){if(!dns)return;await act(async()=>{await api.verifyDomain(dns.asset.id);await api.scanDomain(dns.asset.id);setDns(null);setDomain("")},"Dominio verificado y analizado.")}
 async function createIncident(e:React.FormEvent){e.preventDefault();if(!org)return;await act(async()=>{await api.createIncident(org.id,incident);setIncident({title:"",description:"",severity:"medium"})},"Incidente registrado.")}
 const go=(v:View)=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:"smooth"})};
 if(!session)return <main className="login"><div className="login-card"><Brand/><h1>Protege tu empresa</h1><p>Tu centro de seguridad, explicado sin tecnicismos.</p><form onSubmit={login}><label>Correo electrónico</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@empresa.mx"/><button className="primary" disabled={loading}>{loading?<Loader2 className="spin"/>:"Enviar enlace de acceso"}</button></form>{message&&<div className="notice">{message}</div>}<small className="privacy">Nunca solicitaremos tu contraseña por correo.</small></div></main>;
 const nav:[View,React.ReactNode][]=[["summary",<LayoutDashboard/>],["risks",<ShieldAlert/>],["assets",<Globe2/>],["incidents",<Siren/>],["coach",<BookOpenCheck/>],["history",<History/>],["settings",<Settings/>]];
 return <main className="shell"><aside className={mobile?"open":""}><button className="close" onClick={()=>setMobile(false)}><X/></button><Brand/><div className="company">{org?.name??"TestCompCy"} · PyME</div><nav>{nav.map(([id,icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}>{icon}{labels[id]}{id==="risks"&&open.length>0?<i>{open.length}</i>:null}{id==="incidents"&&active.length>0?<i>{active.length}</i>:null}</button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></aside>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<section className="content"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><small>EJECUTYX CYBER</small><h1>{labels[view]}</h1></div><div className="user"><CircleUserRound/><span>{session.user?.email}</span></div></header>{message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage("")}><X/></button></div>}
 {view==="summary"&&<><div className="hero"><div><small>POSTURA ACTUAL</small><h2>{score>=80?"Tu protección va por buen camino":score?"Tu empresa necesita atención":"Conecta tu primer dominio"}</h2><p>Prioriza lo importante y mejora tu seguridad paso a paso.</p></div><button className="primary" onClick={()=>go("assets")}><Plus/>Agregar dominio</button></div><div className="grid top"><article className="score"><Score value={score}/><div><small>CYBERSCORE EXTERNO</small><h2>{score>=80?"Buena protección":score?"Protección media":"Sin análisis"}</h2><p>HTTPS, correo y configuración pública de dominios autorizados.</p>{trend!==0&&<span className={trend>0?"positive":"negative"}>{trend>0?"+":""}{trend} desde el análisis anterior</span>}</div></article><Kpi label="RIESGOS ABIERTOS" value={open.length} text={open.length?"Corrige primero los de mayor impacto.":"No hay hallazgos abiertos."}/></div><div className="grid"><article><Title eyebrow="PRIORIDAD" title="Acciones recomendadas" icon={<AlertTriangle/>}/>{open.length===0?<Empty text="Sin riesgos abiertos."/>:open.slice(0,4).map(f=><FindingRow key={f.id} f={f} onClick={()=>go("coach")}/>)}</article><article><Title eyebrow="COBERTURA" title="Activos vigilados" icon={<Globe2/>}/><div className="metrics"><div><b>{data.assets.length}</b><span>Dominios</span></div><div><b>{data.history.length}</b><span>Análisis</span></div><div><b>{active.length}</b><span>Incidentes</span></div></div>{data.assets.slice(0,3).map(a=><div className="row" key={a.id}><div><b>{a.value}</b><small>{a.verification_status==="verified"?"Verificado":"Pendiente"}</small></div><span className={`pill ${a.verification_status}`}>{a.verification_status==="verified"?"Protegido":"Por verificar"}</span></div>)}</article></div></>}
 {view==="risks"&&<Page intro="Revisa, acepta temporalmente o resuelve los hallazgos detectados."><p>{open.length} abiertos · {data.findings.filter(f=>f.status==="resolved").length} resueltos</p>{data.findings.length===0?<article><Empty text="Analiza un dominio para buscar riesgos."/></article>:data.findings.map(f=><article className="risk-card" key={f.id}><div className={`severity ${f.severity}`}>{f.severity}</div><div className="grow"><h3>{f.title}</h3><p>{f.evidence}</p><small>{f.control_key} · {fmt(f.detected_at)}</small></div><div className="actions">{f.status!=="resolved"&&<button className="secondary" onClick={()=>void act(()=>api.resolveFinding(f.id,"resolved"),"Riesgo resuelto.")}>Resolver</button>}{f.status==="open"&&<button className="ghost" onClick={()=>void act(()=>api.resolveFinding(f.id,"accepted"),"Riesgo aceptado temporalmente.")}>Aceptar</button>}<span className={`pill ${f.status}`}>{f.status}</span></div></article>)}</Page>}
 {view==="assets"&&<Page intro="Solo analizamos dominios cuya propiedad confirmes mediante DNS."><div className="grid"><article><Title eyebrow="INVENTARIO" title="Dominios autorizados" icon={<Globe2/>}/>{data.assets.length===0?<Empty text="Aún no agregas dominios."/>:data.assets.map(a=><div className="asset" key={a.id}><div><b>{a.value}</b><small>{a.verification_status==="verified"?`Último CyberScore: ${latest.get(a.id)?.score??"sin análisis"}`:"Verificación pendiente"}</small></div>{a.verification_status==="verified"&&<button className="secondary" disabled={loading} onClick={()=>void act(()=>api.scanDomain(a.id),"Análisis terminado.")}><RefreshCw/>Analizar</button>}</div>)}</article><article><Title eyebrow="NUEVO ACTIVO" title="Verificar dominio" icon={<Plus/>}/>{dns?<div className="dns"><p>Publica este registro y espera su propagación:</p><dl><dt>Tipo</dt><dd>{dns.dns.type}</dd><dt>Nombre</dt><dd><code>{dns.dns.name}</code></dd><dt>Valor</dt><dd><code>{dns.dns.value}</code></dd></dl><button className="primary" disabled={loading} onClick={()=>void verify()}><Shield/>Verificar y analizar</button></div>:<form className="stack" onSubmit={addDomain}><label>Dominio de tu empresa</label><input required value={domain} onChange={e=>setDomain(e.target.value)} placeholder="empresa.mx"/><button className="primary" disabled={loading}><Plus/>Crear verificación</button></form>}</article></div></Page>}
 {view==="incidents"&&<Page intro="Registra una sospecha o ataque y conserva una bitácora clara."><div className="grid"><article><Title eyebrow="EMERGENCIA" title="Reportar incidente" icon={<Siren/>}/><form className="stack" onSubmit={createIncident}><label>Título</label><input required minLength={3} value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})} placeholder="Cuenta de correo comprometida"/><label>Severidad</label><select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="critical">Crítica</option><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></select><label>Qué ocurrió</label><textarea value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})} placeholder="Señales, hora y sistemas afectados"/><button className="danger"><Siren/>Registrar incidente</button></form></article><article><Title eyebrow="PROTOCOLO INICIAL" title="Qué hacer ahora" icon={<BookOpenCheck/>}/><ol className="protocol"><li>Aísla el equipo afectado sin apagarlo.</li><li>No borres mensajes, archivos ni registros.</li><li>Cambia credenciales desde un equipo confiable y activa MFA.</li><li>Documenta horas, personas, sistemas y acciones.</li><li>Busca apoyo si hay datos sensibles o fraude.</li></ol></article></div><h2>Bitácora</h2>{data.incidents.length===0?<article><Empty text="No hay incidentes registrados."/></article>:data.incidents.map(i=><article className="risk-card" key={i.id}><div className={`severity ${i.severity}`}>{i.severity}</div><div className="grow"><h3>{i.title}</h3><p>{i.description||"Sin descripción."}</p><small>{fmt(i.created_at)}</small></div><div className="actions">{i.status==="open"&&<button className="secondary" onClick={()=>void act(()=>api.updateIncident(i.id,"contained"),"Incidente contenido.")}>Contener</button>}{i.status!=="resolved"&&<button className="ghost" onClick={()=>void act(()=>api.updateIncident(i.id,"resolved"),"Incidente resuelto.")}>Resolver</button>}<span className={`pill ${i.status}`}>{i.status}</span></div></article>)}</Page>}
 {view==="coach"&&<Page intro="Instrucciones sencillas para corregir cada control."><div className="coach-grid">{Object.entries(guide).map(([key,g])=>{const f=data.findings.find(x=>x.control_key===key&&x.status==="open");return <article className="coach-card" key={key}><div className="coach-icon">{f?<AlertTriangle/>:<CheckCircle2/>}</div><small>{key}</small><h2>{g.title}</h2><p>{g.why}</p><ol>{g.steps.map(s=><li key={s}>{s}</li>)}</ol><span className={`pill ${f?"open":"resolved"}`}>{f?"Requiere acción":"Correcto o sin evaluar"}</span></article>})}</div></Page>}
 {view==="history"&&<Page intro="Consulta CyberScore, comprobaciones y actividad."><div className="grid"><article><Title eyebrow="ANÁLISIS" title="Escaneos" icon={<FileClock/>}/>{data.history.length===0?<Empty text="Aún no hay análisis."/>:data.history.map(s=><div className="timeline" key={s.id}><b>{s.score}/100</b><div><strong>{data.assets.find(a=>a.id===s.asset_id)?.value??"Dominio"}</strong><small>{fmt(s.scanned_at)} · HTTPS {s.checks.https?"✓":"×"} · SPF {s.checks.spf?"✓":"×"} · DMARC {s.checks.dmarc?"✓":"×"}</small></div></div>)}</article><article><Title eyebrow="TRAZABILIDAD" title="Actividad" icon={<Clock3/>}/>{data.audits.length===0?<Empty text="Sin actividad registrada."/>:data.audits.map(a=><div className="timeline" key={a.id}><CheckCircle2/><div><strong>{a.action.replaceAll("."," · ")}</strong><small>{fmt(a.created_at)}</small></div></div>)}</article></div></Page>}
 {view==="settings"&&<Page intro="Datos y controles de acceso de TestCompCy."><div className="grid"><article><Title eyebrow="EMPRESA" title="Perfil" icon={<Building2/>}/><form className="stack" onSubmit={e=>{e.preventDefault();if(org)void act(()=>api.updateOrganization(org.id,{name:company.name,sector:company.sector,employeeCount:company.employeeCount?Number(company.employeeCount):null}),"Empresa actualizada.")}}><label>Nombre</label><input required value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/><label>Sector</label><input value={company.sector} onChange={e=>setCompany({...company,sector:e.target.value})}/><label>Colaboradores</label><input type="number" min="1" value={company.employeeCount} onChange={e=>setCompany({...company,employeeCount:e.target.value})}/><button className="primary">Guardar cambios</button></form></article><article><Title eyebrow="CUENTA" title="Seguridad y acceso" icon={<Shield/>}/><div className="setting-row"><div><b>Sesión por enlace seguro</b><p>{session.user?.email}</p></div><span className="pill verified">Activo</span></div><div className="setting-row"><div><b>Rol</b><p>Permisos en TestCompCy</p></div><span className="pill">{org?.role}</span></div><button className="secondary" onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></article></div></Page>}
 </section></main>
}
function Brand(){return <div className="brand"><span><Shield/></span><b>Ejecutyx <em>Cyber</em></b></div>}; function Page({intro,children}:{intro:string;children:React.ReactNode}){return <div className="page"><p className="intro">{intro}</p>{children}</div>}; function Score({value}:{value:number}){return <div className="ring" style={{"--score":`${value*3.6}deg`} as React.CSSProperties}><span><b>{value}</b><small>de 100</small></span></div>}; function Kpi({label,value,text}:{label:string;value:number;text:string}){return <article className="kpi"><ShieldAlert/><small>{label}</small><div className="big-number">{value}</div><p>{text}</p></article>}; function Title({eyebrow,title,icon}:{eyebrow:string;title:string;icon:React.ReactNode}){return <div className="section-title"><div><small>{eyebrow}</small><h2>{title}</h2></div>{icon}</div>}; function Empty({text}:{text:string}){return <p className="empty"><CheckCircle2/> {text}</p>}; function FindingRow({f,onClick}:{f:Finding;onClick:()=>void}){return <button className="finding" onClick={onClick}><span className={f.severity}/><div><b>{f.title}</b><p>{f.evidence}</p><small>Impacto: {f.score_impact} puntos</small></div><ChevronRight/></button>}
